app/blog/models.py
from .. import db

post_tag = db.Table('post_tag',
                    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                    )


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    def __repr__(self):
        return f'<Tag "{self.name}">'

class Post(db.Model):
    __tablename__ = "post"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.Text)
    comments = db.relationship('Comment', backref='post')
    tags = db.relationship('Tag', secondary=post_tag, backref='posts')
    def __repr__(self):
        return f'<Post "{self.title}">'

class Comment(db.Model):
    __tablename__ = "comment"
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))
    def __repr__(self):
        return f'<Comment "{self.content[:20]}...">'



app/blog/routes.py
import os
from flask import Blueprint, Flask, render_template, request, redirect, url_for
#from flask_sqlalchemy import SQLAlchemy
from .models import Tag, Post, Comment
from .. import db

# https://www.digitalocean.com/community/tutorials/how-to-use-one-to-many-database-relationships-with-flask-sqlalchemy
# https://www.digitalocean.com/community/tutorials/how-to-use-many-to-many-database-relationships-with-flask-sqlalchemy

blog_bp = Blueprint("blog_bp", __name__, template_folder="templates", static_folder="static")

@blog_bp.route('/blog')
def index():
    posts = Post.query.all()
    return render_template('blog/index.html', posts=posts)

@blog_bp.route('/<int:post_id>/', methods=('GET', 'POST'))
def post(post_id):
    post = Post.query.get_or_404(post_id)
    if request.method == 'POST':
        comment = Comment(content=request.form['content'], post=post)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('blog_bp.post', post_id=post.id))
    return render_template('blog/post.html', post=post)

@blog_bp.route('/comments/')
def comments():
    comments = Comment.query.order_by(Comment.id.desc()).all()
    return render_template('blog/comments.html', comments=comments)

@blog_bp.route('/comments/<int:comment_id>/delete')
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    post_id = comment.post.id
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('blog_bp.post', post_id=post_id))

@blog_bp.route('/tags/<tag_name>/')
def tag(tag_name):
    tag = Tag.query.filter_by(name=tag_name).first_or_404()
    return render_template('blog/tag.html', tag=tag)

@blog_bp.route('/load_db', methods=('GET', 'POST'))
def load_db():
    #db.drop_all()
    #db.create_all()

    post1 = Post(title='Post The First', content='Content for the first post')
    post2 = Post(title='Post The Second', content='Content for the Second post')
    post3 = Post(title='Post The Third', content='Content for the third post')
    life_death_post = Post(title='A post on life and death', content='life and death')
    joy_post = Post(title='A post on joy', content='joy')

    comment1 = Comment(content='Comment for the first post', post=post1)
    comment2 = Comment(content='Comment for the second post', post=post2)
    comment3 = Comment(content='Another comment for the second post', post_id=2)
    comment4 = Comment(content='Another comment for the first post', post_id=1)

    tag1 = Tag(name='animals')
    tag2 = Tag(name='tech')
    tag3 = Tag(name='cooking')
    tag4 = Tag(name='writing')
    life_tag = Tag(name='life')
    death_tag = Tag(name='death')
    joy_tag = Tag(name='joy')
    
    post1.tags.append(tag1)  # Tag the first post with 'animals'
    post1.tags.append(tag4)  # Tag the first post with 'writing'
    post3.tags.append(tag3)  # Tag the third post with 'cooking'
    post3.tags.append(tag2)  # Tag the third post with 'tech'
    post3.tags.append(tag4)  # Tag the third post with 'writing'
    life_death_post.tags.append(life_tag)
    life_death_post.tags.append(death_tag)
    joy_post.tags.append(joy_tag)

    db.session.add_all([post1, post2, post3, life_death_post, joy_post])
    db.session.add_all([comment1, comment2, comment3, comment4])
    db.session.add_all([tag1, tag2, tag3, tag4, life_tag, death_tag, joy_tag])

    db.session.commit()
    posts = Post.query.all()
    return render_template('blog/index.html', posts=posts)

app/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - FlaskApp</title>
    <style>
        .title {
            margin: 5px;
        }

        .content {
            margin: 5px;
            width: 100%;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .comment {
            padding: 10px;
            margin: 10px;
            background-color: #fff;
        }

        .post {
            flex: 20%;
            padding: 10px;
            margin: 5px;
            background-color: #f3f3f3;
            inline-size: 100%;
        }

        .title a {
            color: #00a36f;
            text-decoration: none;
        }

        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <nav>
        <a href="{{ url_for('blog_bp.index') }}">FlaskApp</a>
        <a href="{{ url_for('blog_bp.comments') }}">Comments</a>
        <a href="#">About</a>
    </nav>
    <hr>
    <div class="content">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

app/blog/templates/blog/comments.html
{% extends 'base2.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Latest Comments {% endblock %}</h1></span>
    <div class="content">
                {% for comment in comments %}
                    <div class="comment">
                        <i>
                            (#{{ comment.id }})
                            <p>{{ comment.content }}</p>
                        </i>
                        <p class="title">
                        On <a href="{{ url_for('blog_bp.post',
                                                post_id=comment.post.id) }}">
                                {{ comment.post.title }}
                              </a>
                        </p>
                    </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

app/blog/templates/blog/index.html
{% from 'blog/macros.html' import display_tags %}
{% extends 'base2.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} Posts {% endblock %}</h1></span>
    <div class="content">
        {% for post in posts %}
            <div class="post">
                <p><b>#{{ post.id }}</b></p>
                <b>
                    <p class="title">
                        <a href="{{ url_for('blog_bp.post', post_id=post.id)}}">
                            {{ post.title }}
                        </a>
                    </p>
                </b>
                <div class="content">
                    <p>{{ post.content }}</p>
                </div>
		{{ display_tags(post) }}
                <hr>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/blog/templates/blog/macros.html
{% macro display_tags(post) %}
    <div class="tags">
        <p>
            <h4>Tags:</h4>
            {% for tag in post.tags %}
                <a href="{{ url_for('blog_bp.tag', tag_name=tag.name) }}" style="text-decoration: none; color: #dd5b5b">
                    {{ tag.name }}
                </a>
                |
            {% endfor %}
        </p>
    </div>
{% endmacro %}

app/blog/templates/blog/post.html
{% from 'blog/macros.html' import display_tags %}
{% extends 'base2.html' %}

{% block content %}
    <span class="title"><h1>{% block title %} {{ post.title }}  {% endblock %}</h1></span>
    <div class="content">
            <div class="post">
                <p><b>#{{ post.id }}</b></p>
                <b>
                    <p class="title">{{ post.title }}</p>
                </b>
                <div class="content">
                    <p>{{ post.content }}</p>
                </div>

		{{ display_tags(post) }}

                <hr>
                <h3>Comments</h3>

                <form method="post">
                    <p>
                        <textarea name="content"
                                    placeholder="Comment"
                                    cols="60"
                                    rows="5"></textarea>
                    </p>

                    <p>
                        <button type="submit">Add comment</button>
                    </p>
                </form>

                {% for comment in post.comments %}
                    <div class="comment">
                        <p>#{{ comment.id }}</p>
                        <p>{{ comment.content }}</p>
                        <form method="POST"
                            action="{{ url_for('blog_bp.delete_comment',
                                                comment_id=comment.id) }}">
                            <input type="submit" value="Delete Comment"
                                onclick="return confirm('Are you sure you want to delete this entry?')">
                        </form>
                    </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

app/blog/templates/blog/tag.html
{% from 'blog/macros.html' import display_tags %}
{% extends 'base2.html' %}

{% block content %}
    <span class="title">
        <h1>{% block title %} Posts Tagged with "{{ tag.name }}" {% endblock %}</h1>
    </span>
    <div class="content">
        {% for post in tag.posts %}
        <div class="post">
            <p><b>#{{ post.id }}</b></p>
            <b>
                <p class="title">
                    <a href="{{ url_for('blog_bp.post', post_id=post.id)}}">
                        {{ post.title }}
                    </a>
                </p>
            </b>
            <div class="content">
                <p>{{ post.content }}</p>
            </div>

            {{ display_tags(post) }}

            <hr>
        </div>
        {% endfor %}
    </div>
{% endblock %}